server:
  port: 8791

spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            search-paths: /**     # 配置文件所在的目录
            uri: https://github.com/VaieJava/outdd-read-config-files
            username: vaielx@163.com
            password: y571859138
        label: master  # 分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.107.226.36:8761/eureka/