server:
  port: 8762

spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/VaieJava/fenbushi.git
            username: vaielx@163.com
            password: y571859138
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/